# Use the official Golang image for building the application
FROM golang:1.18 AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the source code
COPY . .

# Build the application
RUN go build -o product-service .

# Use a smaller base image for the runtime
FROM alpine:latest

# Set the working directory
WORKDIR /root/

# Copy the built application from the builder image
COPY --from=builder /app/product-service .

# Copy necessary files like configuration, static files, etc.
# COPY ./config /root/config

# Expose the application port
EXPOSE 8080

# Command to run the application
CMD ["./product-service"]
